"""Make client_email unique

Revision ID: c484af9cd2b4
Revises: 
Create Date: 2025-06-15 21:40:39.199655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c484af9cd2b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitness_classes_id'), table_name='fitness_classes')
    op.drop_table('fitness_classes')
    op.create_unique_constraint(None, 'bookings', ['client_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='unique')
    op.create_table('fitness_classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('available_slots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fitness_classes_pkey'))
    )
    op.create_index(op.f('ix_fitness_classes_id'), 'fitness_classes', ['id'], unique=False)
    # ### end Alembic commands ###
